<%@ Page Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="CheckOutForm.aspx.cs"
    Inherits="CheckOutForm" %>

<%@ Register Assembly="CKEditor.NET" Namespace="CKEditor.NET" TagPrefix="CKEditor" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="Server">
    <%--<link href="../Styles/Site.css" rel="stylesheet" type="text/css" />--%>
    <link href="../Styles/crew_css.css" rel="stylesheet" type="text/css" />
    <link href="../Styles/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="../Scripts/jquery.min.js" type="text/javascript"></script>
    <script src="../Scripts/jquery-ui.min.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.core.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.draggable.js" type="text/javascript"></script>
    <script src="../Scripts/modalpopup.js" type="text/javascript"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="Server">
    <asp:UpdateProgress ID="upUpdateProgress" runat="server">
        <ProgressTemplate>
            <div id="divProgress" style="background-color: transparent; position: absolute; left: 49%;
                top: 20px; z-index: 2; color: black">
                <img src="../images/loaderbar.gif" alt="Please Wait" />
            </div>
        </ProgressTemplate>
    </asp:UpdateProgress>
    <br />
    <div id="divMessage" align="center">
        <asp:Label ID="dvMessage" runat="server" ForeColor="Blue" Font-Size="Medium"></asp:Label>
    </div>
    <br />
    <div>
        <table width="100%">
            <tr>
                <td valign="top">
                    <div>
                        <asp:UpdatePanel ID="UpdatePanel_west" runat="server">
                            <ContentTemplate>
                                <div class="gradiant-css-orange" style="font-size: 14px; padding: 4px; text-align: center;">
                                    <div style="float: right">
                                        <img src="../images/Pin_Off.png" />
                                    </div>
                                    Procedure Section
                                </div>
                                <div class="toolbox">
                                    <asp:Label ID="lblLoginInfo" runat="server"></asp:Label>
                                </div>                               
                                <div style="background-color: #f8f8f8; text-align: left; height: 300px; width: 250px;
                                    overflow: auto; z-index: 1; border: 1px solid inset;">
                                    <div style="position: absolute; color: Black; overflow: auto; width: 230px; text-align: right;">
                                        <asp:ImageButton ID="btnRefresh" runat="server" Text="Refresh" ImageUrl="../Images/refresh.png" />
                                        <asp:Label ID="lblProcedureId" runat ="server" Width ="20"></asp:Label>
                                    </div>
                                    <asp:TreeView ID="BrowseTreeView" runat="server" Style="margin-right: 1px" BorderColor="#F3F1CD"
                                        Font-Bold="False" Font-Names="Arial" Font-Size="Small" ForeColor="Black" EnableViewState="False"
                                        ImageSet="XPFileExplorer" NodeIndent="15" AutoGenerateDataBindings="False">
                                        <ParentNodeStyle Font-Bold="False" />
                                        <HoverNodeStyle Font-Underline="False" ForeColor="#6666AA" BackColor="#99FF66" />
                                        <SelectedNodeStyle Font-Underline="False" ForeColor="#6666AA" BackColor="#99FF66" />
                                        <NodeStyle Font-Names="Tahoma" Font-Size="8pt" ForeColor="Black" HorizontalPadding="2px"
                                            NodeSpacing="0px" VerticalPadding="2px" />
                                    </asp:TreeView>
                                </div>
                                <div class="toolbox-header">
                                    Saved Procedures
                                </div>
                                 <div class="toolbox-header">
                                    <asp:Button ID="btnNewSection" runat="server" Text="Add Section" BorderStyle="Solid"
                                        OnClick="btnSaveQueryAs_Click" BorderColor="#0489B1" BorderWidth="1px" Font-Names="Tahoma"
                                        Height="24px" BackColor="#81DAF5" />
                                </div>
                            </ContentTemplate>
                        </asp:UpdatePanel>
                    </div>
                </td>
                <td valign="top">
                    <div style="text-align: left; vertical-align: top; background-color: Aqua;">
                        <asp:UpdatePanel ID="UpdatePanel_Center" runat="server">
                            <ContentTemplate>
                                <div  class="gradiant-css-orange" style="font-size: 14px; padding: 4px">
                                    <div style="float: right">
                                        <img src="../images/xf_maximize_icon.png" id="maximize-icon" />
                                    </div>
                                    <img src="../images/wizard/database-process-icon.png" style="vertical-align: bottom"
                                        height="20px" />
                                    &nbsp;&nbsp; Section Builder</div>
                                <asp:Panel ID="pnlCtl" runat="server" Visible="true">
                                    <asp:Button ID="btnSave" runat="server" Text="Save Procedure" BorderStyle="Solid"
                                        OnClick="btnSave_Click" BorderColor="#0489B1" BorderWidth="1px" Font-Names="Tahoma"
                                        Height="24px" BackColor="#81DAF5" />
                                    <asp:Button ID="btnFinalize" runat="server" Text="Save and Finalize Procedure" BorderStyle="Solid"
                                        OnClick="btnFinalize_Click" BorderColor="#0489B1" BorderWidth="1px" Font-Names="Tahoma"
                                        Height="24px" BackColor="#81DAF5" />
                                    <asp:Button ID="btnSendTo" runat="server" Text="Send for Appoval" BorderStyle="Solid"
                                        OnClick="btnSendTo_Click" BorderColor="#0489B1" BorderWidth="1px" Font-Names="Tahoma"
                                        Height="24px" BackColor="#81DAF5" />
                                </asp:Panel>
                                <div style="text-align: left; vertical-align: top;">
                                    <CKEditor:CKEditorControl ID="txtProcedureSectionDetails" CssClass="cke_show_borders text-editor"
                                        runat="server" Height="800px" Width="100%"></CKEditor:CKEditorControl>
                                    <asp:Label ID="lblCreatedBy" runat="server"></asp:Label>
                                </div>
                            </ContentTemplate>
                        </asp:UpdatePanel>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div id="AddNewSection" title="Add Section" style="border: 1px solid #efefef; padding: 10px;
        margin-top: 2px; display: none; width: 420px;">
        <asp:UpdatePanel ID="UpdatePanelAddSection" runat="server">
            <ContentTemplate>
                <asp:Panel ID="pnllAddSection" runat="server" Visible="true">
                    <table cellpadding="2" cellspacing="0" style="border: 1px solid #dcdcdc; width: 100%;">
                        <tr>
                            <td style="vertical-align: top;">
                                <asp:Label ID="lblSection" runat="server" Text="Section Name" Enabled="true"></asp:Label>
                            </td>
                            <td align="left">
                                <asp:TextBox ID="txtSectionName" runat="server" Width="240px" Enabled="true"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td style="vertical-align: top;">
                                <asp:Label ID="lblSectionHeader" runat="server" Text="Header Name"></asp:Label>
                            </td>
                            <td align="left">
                                <asp:TextBox ID="txtSectionHeader" runat="server" TextMode="MultiLine" Rows="5" Width="240px"
                                    Enabled="true"></asp:TextBox>
                            </td>
                            <td>
                            </td>
                        </tr>
                        <tr>
                            <td style="vertical-align: top;">
                                <asp:Label ID="Label1" runat="server" Text="Section"></asp:Label>
                            </td>
                            <td align="left">
                                <asp:DropDownList ID="ddlSection" runat="server" Width="120px">
                                </asp:DropDownList>
                            </td>
                            <td>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" align="center">
                                <asp:Button ID="btnSaveSection" runat="server" Text="Save" BorderStyle="Solid" OnClick="btnSaveSection_Click"
                                    BorderColor="#0489B1" BorderWidth="1px" Font-Names="Tahoma" Height="24px" BackColor="#81DAF5" />
                                <asp:Button ID="btnCancelSction" runat="server" Text="Cancel" BorderStyle="Solid"
                                    OnClick="btnCancelSction_Click" BorderColor="#0489B1" BorderWidth="1px" Font-Names="Tahoma"
                                    Height="24px" BackColor="#81DAF5" />
                            </td>
                        </tr>
                    </table>
                </asp:Panel>
            </ContentTemplate>
        </asp:UpdatePanel>
    </div>
    <div id="DivSendForApp" title="Approval" style="border: 1px solid #efefef; padding: 10px;
        margin-top: 2px; display: none; width: 400px;">
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <asp:Panel ID="Panel2" runat="server" Visible="true">
                    <table cellpadding="2" cellspacing="0" style="border: 1px solid #dcdcdc; width: 100%;">
                        <tr>
                            <td style="vertical-align: top;">
                                <asp:Label ID="lblUser" runat="server" Text="Send To" Enabled="true"></asp:Label>
                            </td>
                            <td align="left">
                                <asp:DropDownList ID="lstUser" runat="server" Width="230px" SelectionMode="Multiple"
                                    DataTextField="UserName" DataValueField="UserID">
                                </asp:DropDownList>
                            </td>
                        </tr>
                        <tr>
                            <td style="vertical-align: top;">
                                <asp:Label ID="lblWorkStatus" runat="server" Text="For Work"></asp:Label>
                            </td>
                            <td align="left">
                                <asp:DropDownList ID="ddlStatus" runat="server" Width="230px">
                                    <asp:ListItem Text="Approval" Value="Approval"></asp:ListItem>
                                    <asp:ListItem Text="Send For Approval" Value="Send For Approval"></asp:ListItem>
                                    <asp:ListItem Text="Re-Work" Value="Re-Work"></asp:ListItem>
                                </asp:DropDownList>
                            </td>
                            <td>
                            </td>
                        </tr>
                        <tr>
                            <td style="vertical-align: top;">
                                <asp:Label ID="lblComments" runat="server" Text="Comments"></asp:Label>
                            </td>
                            <td align="left">
                                <asp:TextBox ID="txtComments" runat="server" TextMode="MultiLine" Rows="5" Width="240px"
                                    Enabled="true"></asp:TextBox>
                            </td>
                            <td>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" align="center">
                                <asp:Button ID="btnSendApproval" runat="server" Text="Save" BorderStyle="Solid" OnClick="btnSendForApproval_Click"
                                    BorderColor="#0489B1" BorderWidth="1px" Font-Names="Tahoma" Height="24px" BackColor="#81DAF5" />
                                <asp:Button ID="btnCancelSend" runat="server" Text="Cancel" BorderStyle="Solid" OnClick="btnCancelApp_Click"
                                    BorderColor="#0489B1" BorderWidth="1px" Font-Names="Tahoma" Height="24px" BackColor="#81DAF5" />
                            </td>
                        </tr>
                    </table>
                </asp:Panel>
            </ContentTemplate>
        </asp:UpdatePanel>
    </div>
    <div id="dvUploadimage" style="position: absolute; left: 35%; top: 35%; display: none;
        border: 3px solid #66CCFF; background-color: #F7F7F7; height: 200px; width: 400px;
        overflow: auto; z-index: 1000">
        <table style="background-color: #66CCFF; width: 100%" cellpadding="0" cellspacing="0">
            <tr>
                <td style="width: 70%; font-family: Tahoma; font-size: 12px; font-weight: bold; text-align: left;
                    padding: 5px">
                    Insert Image
                </td>
                <td style="width: 70%; text-align: right">
                    <img onclick="javascript:document.getElementById('dvUploadimage').style.display = 'none';"
                        alt="close" src="../images/close.gif" />
                </td>
            </tr>
        </table>
        <table style="width: 100%;">
            <tr>
                <td align="left">
                    <asp:UpdatePanel ID="upsd" UpdateMode="Conditional" runat="server">
                        <ContentTemplate>
                            <asp:Label runat="server" ID="myThrobber" Style="display: none;"><img align="absmiddle" alt="" src="uploading.gif"/></asp:Label>
                            <tlk4:AjaxFileUpload ID="AjaxFileUploadInsertImage" runat="server" Padding-Bottom="2"
                                Padding-Left="2" Padding-Right="1" Padding-Top="2" ThrobberID="myThrobber" OnUploadComplete="AjaxFileUploadInsertImage_OnUploadComplete"
                                MaximumNumberOfFiles="10" />
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
