<%@ Page Title="PMS" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true"
    CodeFile="Functional_Tree.aspx.cs" Inherits="Technical_PMS_Functional_Tree" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="Server">

 <div class="page-title">
        Functional Tree
    </div>
    <div class="page-content">
    <asp:UpdatePanel ID="updMain" runat="server">
        <ContentTemplate>
            <table>
                <tr>
                    <td align="right" style="width: 10%">
                        Fleet : &nbsp;
                    </td>
                    <td align="left">
                        <asp:DropDownList ID="DDLFleet" runat="server" AppendDataBoundItems="True" 
                            AutoPostBack="true" Font-Size="11px" Height="20px" 
                            OnSelectedIndexChanged="DDLFleet_SelectedIndexChanged" Width="124px">
                            <asp:ListItem Selected="True" Value="0">--SELECT ALL--</asp:ListItem>
                        </asp:DropDownList>
                    </td>
                    <td align="right" style="width: 10%">
                        Vessel : &nbsp;
                    </td>
                    <td align="left">
                        <asp:DropDownList ID="DDLVessel" runat="server" AutoPostBack="true" 
                            Font-Size="11px" Height="20px" 
                            onselectedindexchanged="DDLVessel_SelectedIndexChanged" Width="124px">
                        </asp:DropDownList>
                    </td>
                </tr>
            </table>
            <div>
                <div style="float: left; width: 25%">
                    <asp:TreeView ID="tvItemList" runat="server" Style="margin-right: 1px" BorderColor="#F3F1CD"
                        Font-Bold="False" Font-Names="Arial" Font-Size="Small" ForeColor="Black" EnableViewState="true"
                        ImageSet="XPFileExplorer" NodeIndent="15" AutoGenerateDataBindings="False" OnSelectedNodeChanged="tvItemList_SelectedNodeChanged">
                        <ParentNodeStyle Font-Bold="False" />
                        <HoverNodeStyle Font-Underline="False" ForeColor="#6666AA" BackColor="#99FF66" />
                        <SelectedNodeStyle Font-Underline="False" ForeColor="#6666AA" BackColor="#99FF66" />
                        <NodeStyle Font-Names="Tahoma" Font-Size="8pt" ForeColor="Black" HorizontalPadding="2px"
                            NodeSpacing="0px" VerticalPadding="2px" />
                    </asp:TreeView>
                </div>
                <div style="float: right; width: 72%;margin:10px">
                    <asp:GridView ID="gvJobs" runat="server" AutoGenerateColumns="False" Width="100%"
                        CellPadding="4" EmptyDataText="No job found !" AllowSorting="true" DataKeyNames="ID">
                        <HeaderStyle CssClass="PMSGridHeaderStyle-css" />
                        <RowStyle CssClass="PMSGridRowStyle-css" />
                        <AlternatingRowStyle CssClass="PMSGridAlternatingRowStyle-css" />
                        <SelectedRowStyle BackColor="#FFFFCC" />
                        <EmptyDataRowStyle ForeColor="Red" HorizontalAlign="Center" Font-Bold="true" Font-Size="12px" />
                        <Columns>
                            <asp:TemplateField HeaderText="Job ID">
                                <ItemTemplate>
                                    <asp:Label ID="lblJobID" Visible="true" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.ID") %>'></asp:Label>
                                    <asp:Label ID="lblJobDescription" Visible="false" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.Job_Description") %>'></asp:Label>
                                    <asp:Label ID="lblItemActiveSatus" Visible="false" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.Active_Status") %>'></asp:Label>
                                    <asp:Label ID="lblVesselID" Visible="false" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.Vessel_ID") %>'></asp:Label>
                                </ItemTemplate>
                                <ItemStyle Wrap="true" HorizontalAlign="Center" CssClass="PMSGridItemStyle-css">
                                </ItemStyle>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Title">
                                <ItemTemplate>
                                    <%# DataBinder.Eval(Container,"DataItem.Job_Title") %>
                                </ItemTemplate>
                                <ItemStyle Wrap="true" HorizontalAlign="Left" Width="450px" CssClass="PMSGridItemStyle-css">
                                </ItemStyle>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Freq.">
                                <HeaderTemplate>
                                    <asp:Label ID="lblFrequencyHeader" runat="server" ForeColor="White">Freq.&nbsp;</asp:Label>
                                </HeaderTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblFrequency" Visible="true" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.Frequency") %>'></asp:Label>
                                </ItemTemplate>
                                <ItemStyle Wrap="true" HorizontalAlign="Center" CssClass="PMSGridItemStyle-css">
                                </ItemStyle>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Freq.type">
                                <HeaderTemplate>
                                    <asp:Label ID="lblFrequencyTypeHeader" runat="server" ForeColor="White">Freq.type&nbsp;</asp:Label>
                                </HeaderTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblFrequencyType" Visible="true" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.Frequency_Name") %>'></asp:Label>
                                </ItemTemplate>
                                <ItemStyle Wrap="true" HorizontalAlign="Center" CssClass="PMSGridItemStyle-css">
                                </ItemStyle>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Department">
                                <HeaderTemplate>
                                    <asp:Label ID="lblDepartmentHeader" runat="server" ForeColor="White">Dept&nbsp;</asp:Label>
                                </HeaderTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblDepartment" Visible="true" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.Department") %>'></asp:Label>
                                </ItemTemplate>
                                <ItemStyle Wrap="true" HorizontalAlign="Center" CssClass="PMSGridItemStyle-css">
                                </ItemStyle>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Rank">
                                <HeaderTemplate>
                                    <asp:Label ID="lblRankNameHeader" runat="server" ForeColor="White">Rank&nbsp;</asp:Label>
                                </HeaderTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblRankName" Visible="true" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.RankName") %>'></asp:Label>
                                </ItemTemplate>
                                <ItemStyle Wrap="true" HorizontalAlign="Left" CssClass="PMSGridItemStyle-css"></ItemStyle>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="CMS">
                                <HeaderTemplate>
                                    <asp:Label ID="lblCMSHeader" runat="server" ForeColor="White">CMS&nbsp;</asp:Label>
                                </HeaderTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblCMS" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.CMS") %>'></asp:Label>
                                </ItemTemplate>
                                <ItemStyle Wrap="true" HorizontalAlign="Center" CssClass="PMSGridItemStyle-css">
                                </ItemStyle>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Critical">
                                <HeaderTemplate>
                                    <asp:Label ID="lblCriticalHeader" runat="server" ForeColor="White">Critical&nbsp;</asp:Label>
                                </HeaderTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblCritical" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.Critical") %>'></asp:Label>
                                </ItemTemplate>
                                <ItemStyle Wrap="true" HorizontalAlign="Center" CssClass="PMSGridItemStyle-css">
                                </ItemStyle>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                </div>
            </div>
        </ContentTemplate>
    </asp:UpdatePanel>
    </div>
</asp:Content>
