 
 
<%@ Page Title="QMS Sync Approval" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true"
    CodeFile="QMSSyncApproval.aspx.cs" Inherits="QMSSyncApproval" %>

<%@ Register Src="../UserControl/ucCustomDropDownList.ascx" TagName="ucCustomDropDownList"
    TagPrefix="ucDDL" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<%@ Register Src="~/UserControl/ucCustomPager.ascx" TagName="ucCustomPager" TagPrefix="uc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="Server">
    <link href="../Styles/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="../Scripts/jquery.min.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.widget.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.core.js" type="text/javascript"></script>
    <script src="../Scripts/jquery-ui.min.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.draggable.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.mouse.js" type="text/javascript"></script>
    <script src="../Scripts/ModalPopUp.js" type="text/javascript"></script>
    <link href="../Styles/smscss_blue.css" rel="stylesheet" type="text/css" />
    <link href="../Purchase/styles/Purchase.css" rel="stylesheet" type="text/css" />
     <script src="../Scripts/JSCustomFilterControls.js" type="text/javascript"></script>
    <script src="../Scripts/ucCustomDropDownList.js" type="text/javascript"></script>
    <link href="../Styles/CssCustomFilterControls.css" rel="stylesheet" type="text/css" />
    <script language="javascript" type="text/javascript">

        function validation() {

            if (document.getElementById("ctl00_MainContent_txtRemark").value == "") {
                alert("Please enter remark.");
                document.getElementById("ctl00_MainContent_txtRemark").focus();
                return false;
            }

            return true;
        }

        function DocOpen(filename) {

            var filepath = "../QMS/";
            //alert(filepath + filename);
            window.open(filepath + filename);
        }


    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="Server">
    <center>
        <asp:UpdateProgress ID="upUpdateProgress" runat="server">
            <ProgressTemplate>
                <div id="blur-on-updateprogress">
                    &nbsp;</div>
                <div id="divProgress" style="position: absolute; left: 49%; top: 30px; z-index: 201;
                    color: black">
                    <img src="../../Images/loaderbar.gif" alt="Please Wait" />
                </div>
            </ProgressTemplate>
        </asp:UpdateProgress>
        <div style="border: 1px solid #cccccc; font-family: Tahoma; font-size: 12px; width: 95%;
            height: 100%;">
           <div class="page-title">
          QMS Sync Approval
        </div>
            <div style="height: 650px; width: 100%; color: Black;">
                <asp:UpdatePanel ID="UpdUserType" runat="server">
                    <ContentTemplate>
                        <div style="padding-top: 5px; padding-bottom: 5px; height: 40px; width: 100%">
                            <table width="100%" cellpadding="4" cellspacing="4">
                                <tr>
                                    <td align="right" style="width: 25%">
                                        Search by File Name :&nbsp;
                                    </td>
                                    <td align="left" style="width: 20%">
                                        <asp:TextBox ID="txtfilter" runat="server" Width="230" CssClass="txtInput"></asp:TextBox>
                                        
                                    </td>
                                    <td align="left" style="width: 20%">
                                        <asp:RadioButtonList ID="optApprove" runat="server" RepeatDirection="Horizontal">
                                          <asp:ListItem Value="0" Text="Not Synced" Selected="True"></asp:ListItem>
                                            <asp:ListItem Value="1" Text="Synced" ></asp:ListItem>
                                          
                                        </asp:RadioButtonList>
                                     
                                    </td>
                                    <td>
                                       <asp:CheckBox id="chkRequireSync" runat="server" Text="Download Required" Checked="true" Visible="false"/></td>
                                    <td align="center" style="width: 5%">
                                        <asp:ImageButton ID="btnFilter" runat="server" TabIndex="0" OnClick="btnFilter_Click"
                                            ToolTip="Search" ImageUrl="~/Images/SearchButton.png" />
                                    </td>
                                    <td align="center" style="width: 5%">
                                        <asp:ImageButton ID="btnRefresh" runat="server" OnClick="btnRefresh_Click" ToolTip="Refresh"
                                            ImageUrl="~/Images/Refresh-icon.png" />
                                    </td>
                                    <td style="width: 5%">
                                        <asp:ImageButton ID="ImgExpExcel" runat="server" ToolTip="Export to excel" OnClick="ImgExpExcel_Click"
                                            ImageUrl="~/Images/Exptoexcel.png" />
                                    </td>
                                </tr>
                                <tr>
                                  <td align="right" style="width: 25%">
                                        Download Size Range :&nbsp;
                                    </td>
                                     <td align="left" style="width: 20%">
                                          <ucDDL:ucCustomDropDownList ID="ddlSizeRange"  runat="server" UseInHeader="false"  
                                 Width="234" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                       <br/> <br/>
                        <div style="margin-left: auto; margin-right: auto; text-align: center;">
                            <div style="text-align: left; ">
                                <span style="color:Red">*</span>Files that required to be downloaded synced 
                                manually
                            </div>
							 
                            <div style="text-align: right; width: 100%">
                                <asp:Button ID="btnDownloadFiles" runat="server" Height="30px" 
                                    onclick="btnDownloadFiles_Click" style="margin-right:24px" 
                                    Text="Download Fiiles" Width="150px" />
                                <asp:Button ID="btnApprove" runat="server" Height="30px" 
                                    OnClick="btnApprove_Click" Text="Sync File(s)" Width="250px" />
                            </div>
							 <br/>
                            <div>
                                <asp:GridView ID="gvQMSFile" runat="server" AllowSorting="true" 
                                    AutoGenerateColumns="False" CellPadding="2" CellSpacing="0" 
                                    DataKeyNames="FilePath" EmptyDataText="NO RECORDS FOUND" GridLines="both" 
                                    OnRowDataBound="gvQMSFile_RowDataBound" OnSorting="gvQMSFile_Sorting" 
                                    Width="100%">
                                    <HeaderStyle CssClass="PMSGridHeaderStyle-css" />
                                    <RowStyle CssClass="PMSGridRowStyle-css" Font-Size="12px" />
                                    <AlternatingRowStyle CssClass="PMSGridAlternatingRowStyle-css" />
                                    <PagerStyle CssClass="PMSPagerStyle-css" />
                                    <SelectedRowStyle BackColor="#FFFFCC" />
                                    <EmptyDataRowStyle Font-Bold="true" Font-Size="12px" ForeColor="Red" 
                                        HorizontalAlign="Center" />
                                    <Columns>
                                        <asp:TemplateField HeaderText="Vessel">
                                            <HeaderTemplate>
                                                <asp:LinkButton ID="lblLogFileIDHeader" runat="server" 
                                                    CommandArgument="LogFileID" CommandName="Sort" ForeColor="Black">File Name&nbsp;</asp:LinkButton>
                                                <img id="LogFileID" runat="server" visible="false" />
                                            </HeaderTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="lblDwR" runat="server" ForeColor="Red" Text="*" 
                                                    Visible='<%#Convert.ToString(Eval("DwdReq"))=="1"?true : false %>' />
                                                <asp:LinkButton ID="lblLogFileID" runat="server" Style="color: Black" 
                                                    Text='<%#Eval("LogFileID")%>'></asp:LinkButton>
                                                <asp:Label ID="lblID" runat="server" Style="color: Black" 
                                                    Text='<%#Eval("ID")%>' Visible="false"></asp:Label>
                                                <asp:Label ID="lblFilePath" runat="server" Style="color: Black" 
                                                    Text='<%#Eval("FilePath")%>' Visible="false"></asp:Label>
                                                <asp:Label ID="lblVersion" runat="server" Style="color: Black" 
                                                    Text='<%#Eval("Version")%>' Visible="false"></asp:Label>
                                            </ItemTemplate>
                                            <ItemStyle CssClass="PMSGridItemStyle-css" HorizontalAlign="Left" Width="120px" 
                                                Wrap="true" />
                                            <HeaderStyle HorizontalAlign="Left" Wrap="true" />
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="File Path" Visible="true">
                                            <HeaderTemplate>
                                                File Path
                                            </HeaderTemplate>
                                            <ItemTemplate>
                                                <%#Eval("FilePath")%>
                                            </ItemTemplate>
                                            <ItemStyle CssClass="PMSGridItemStyle-css" HorizontalAlign="Left" Width="150px" 
                                                Wrap="true" />
                                            <HeaderStyle HorizontalAlign="Left" Wrap="true" />
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Created Date">
                                            <HeaderTemplate>
                                                Created Date
                                            </HeaderTemplate>
                                            <ItemTemplate>
                                                <%#Eval("LogDate")%>
                                            </ItemTemplate>
                                            <ItemStyle CssClass="PMSGridItemStyle-css" HorizontalAlign="Left" Width="70px" 
                                                Wrap="true" />
                                            <HeaderStyle HorizontalAlign="Left" Wrap="true" />
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Version">
                                            <HeaderTemplate>
                                                Version
                                            </HeaderTemplate>
                                            <ItemTemplate>
                                                <%#Eval("Version")%>
                                            </ItemTemplate>
                                            <ItemStyle CssClass="PMSGridItemStyle-css" HorizontalAlign="Center" 
                                                Width="30px" Wrap="true" />
                                            <HeaderStyle HorizontalAlign="Left" Wrap="true" />
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="File Size">
                                            <HeaderTemplate>
                                                File Size (KB)
                                            </HeaderTemplate>
                                            <ItemTemplate>
                                                <%# Eval("SIZE", "{0:0.00}") %>
                                            </ItemTemplate>
                                            <ItemStyle CssClass="PMSGridItemStyle-css" HorizontalAlign="Left" Width="60px" 
                                                Wrap="true" />
                                            <HeaderStyle HorizontalAlign="Left" Wrap="true" />
                                        </asp:TemplateField>
                                        <asp:TemplateField>
                                            <ItemTemplate>
                                                <asp:CheckBox ID="chkStatus" runat="server" 
                                                    Enabled='<%#Convert.ToString(Eval("SendToOffice"))=="N"?true : false %>' 
                                                    Visible='<%#Convert.ToString(Eval("SendToOffice"))=="N"?true : false %>' />
                                                <asp:Image runat="server" Height="16px" ImageUrl="~/Images/Ok-icon.png" 
                                                    Visible='<%#Convert.ToString(Eval("SendToOffice"))=="Y"?true : false %>' />
                                            </ItemTemplate>
                                            <ItemStyle CssClass="PMSGridItemStyle-css" HorizontalAlign="Center" 
                                                Width="80px" Wrap="true" />
                                            <HeaderStyle HorizontalAlign="Center" Wrap="true" />
                                        </asp:TemplateField>
                                    </Columns>
                                </asp:GridView>
                                <uc1:ucCustomPager ID="ucCustomPagerItems" runat="server" 
                                    OnBindDataItem="BindGrid" PageSize="30" />
                                <asp:HiddenField ID="HiddenFlag" runat="server" EnableViewState="False" />
                            </div>
                            <br />
                        </div>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                        </br>
                    </ContentTemplate>
                    <Triggers>
                        <asp:PostBackTrigger ControlID="ImgExpExcel" />
                    </Triggers>
                </asp:UpdatePanel>
            </div>
        </div>
    </center>
</asp:Content>
